# Generated by Django 5.1.2 on 2025-06-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('letra', 'Letra'), ('cifra', 'Cifra'), ('partitura', 'Partitura'), ('audio', 'Audio')], default='TENOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='suit',
            field=models.CharField(choices=[('ALTO', 'Alto'), ('TENOR', 'Tenor'), ('BARITONO', 'Baritono'), ('SOPRANO', 'Soprano'), ('BAIXO', 'Baixo')], default='TENOR', max_length=20),
        ),
    ]
