# Generated by Django 5.1.2 on 2025-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('partitura', 'Partitura'), ('cifra', 'Cifra'), ('letra', 'Letra'), ('audio', 'Audio')], default='TENOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='suit',
            field=models.CharField(choices=[('ALTO', 'Alto'), ('TENOR', 'Tenor'), ('SOPRANO', 'Soprano'), ('BAIXO', 'Baixo'), ('BARITONO', 'Baritono')], default='TENOR', max_length=20),
        ),
    ]
