# Generated by Django 5.1.2 on 2025-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_file_type_alter_member_suit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='terms_agreed',
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('partitura', 'Partitura'), ('audio', 'Audio'), ('cifra', 'Cifra'), ('letra', 'Letra')], default='TENOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='suit',
            field=models.CharField(choices=[('BARITONO', 'Baritono'), ('BAIXO', 'Baixo'), ('TENOR', 'Tenor'), ('ALTO', 'Alto'), ('SOPRANO', 'Soprano')], default='TENOR', max_length=20),
        ),
    ]
