# Generated by Django 5.1.2 on 2025-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_member_terms_agreed_alter_file_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.RemoveField(
            model_name='musicmember',
            name='created_at',
        ),
        migrations.AddField(
            model_name='musicmember',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musicmember',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('cifra', 'Cifra'), ('letra', 'Letra'), ('partitura', 'Partitura'), ('audio', 'Audio')], default='TENOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='suit',
            field=models.CharField(choices=[('SOPRANO', 'Soprano'), ('TENOR', 'Tenor'), ('BAIXO', 'Baixo'), ('ALTO', 'Alto'), ('BARITONO', 'Baritono')], default='TENOR', max_length=20),
        ),
    ]
